<?php
/*
* Copyright (c) 2016 www.magebuzz.com
*/
if ($this->showFeaturedManufacturers()):?>
  <div class="featured-manufacturers">
    <?php $featuredManufacturers = $this->getFeaturedManufacturers(); ?>
    <?php if (count($featuredManufacturers)): ?>
      <h1><?php echo $this->__("Featured Brands"); ?></h1>
        <?php $i = 0;
        foreach ($featuredManufacturers as $featuredManu): $i++ ?>
            <div class="mage_brand_container">
                <a href="<?php echo $this->getManufacturerUrl($featuredManu->getId()); ?>"
                   title="<?php echo $featuredManu->getName(); ?>" target="_blank" class="img">
                    <div class="mage_brand_logo">
                      <img id="img<?php echo $i; ?>"
                             src="<?php echo $this->getFeaturedImage($featuredManu->getImage()) ?>"
                             alt="<?php echo $featuredManu->getName(); ?>" />
                    </div>
                    <div class="mage_brand_title"><?php echo $featuredManu->getName(); ?></div>
                </a>
            </div>
        <?php endforeach ?>
    <?php endif; ?>
  </div>
<?php else: ?>
    <p class="note-msg"><?php echo $this->__('There are no manufacturer matching the selection.') ?></p>
<?php endif; ?>