<?php
/*
* Copyright (c) 2016 www.magebuzz.com
*/
?><?php if ($menu = $this->getManufacturers()): ?>
    <div id="magebuzz_brands_menu_container" style="display: none">
        <li class="brands-menu level0 nav-99 level-top last parent">
            <a href="<?php echo $this->getUrl("manufacturer"); ?>" class="level-top megamenu-lable">
                <span class="brand-title"><?php echo $this->__("Featured Brands"); ?></span>
            </a>
            <div class="magestore-megamenu">
                <div class="sub-menu">
                    <ul class="level0 level0-megamenu">
                        <?php
                        $key = 1;
                        foreach ($menu as $item): ?>
                            <li class="level1 nav-99-<?php echo $key++; ?> <?php echo $key - 1 == 1 ? 'first' : ''; ?> <?php echo $key - 1 == $menu->getSize() ? 'last' : ''; ?>">
                                <a href="<?php echo $this->getManufacturerUrl($item->getId()); ?>">
                            <span>
                                <?php echo $item->getName(); ?>
                            </span>
                                </a>
                            </li>
                        <?php endforeach;?>
                    </ul>
                </div>
            </div>
        </li>
    </div>
    <script type="text/javascript">
        menu = $$('.nav-primary').first() ? $$('.nav-primary').first() : $('nav');
        if (menu) {
            menu.insert($('magebuzz_brands_menu_container').innerHTML);
        }
    </script>
<?php endif; ?>


<!-- Mobile integration -->
<?php if ($menu = $this->getManufacturers()): ?>
    <div id="magebuzz_menu_mobile_container" style="display: none">
        <div class="MenuContainer Parent SubMenu">
            <h2>
                <a href="<?php echo $this->getUrl("manufacturer"); ?>" >
                    <span class="brand-title"><?php echo $this->__("Featured Brands"); ?></span>
                </a><i class="fa fa-plus"></i><i class="fa fa-minus"></i>
            </h2>
            <div class="SubMenuParent">
                <ul class="level0 level0-megamenu">
                    <?php
                    $key = 1;
                    foreach ($menu as $item): ?>
                        <div class="menu no-parent">
                            <a href="<?php echo $this->getManufacturerUrl($item->getId()); ?>">
                            <span>
                                <?php echo $item->getName(); ?>
                            </span>
                            </a>
                        </div>
                    <?php endforeach;?>
                </ul>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        menu = $$('.innerMobMenu').first() ? $$('.innerMobMenu').first() : $('nav');
        if (menu) {
            menu.insert($('magebuzz_menu_mobile_container').innerHTML);
        }
    </script>
<?php endif; ?>