<?php
/*
* Copyright (c) 2016 www.magebuzz.com
*/
if ($this->showManufacturerInProduct()) { ?>
    <div class="shopbybrands-brand-page">
        <?php
          $manufacturer_option_id = $this->getProduct()->getData(Mage::helper('manufacturer')->getConfigAttributrCode());
          $manufacturer = $this->getManufacturerByProductId($manufacturer_option_id);
          if (isset($manufacturer) && $manufacturer->getId()) { ?>
              <img class="display-both-image" src="<?php echo Mage::helper('manufacturer')->getManufacturerImage($manufacturer->getImage()) ?>" />
          <?php }
        } ?>
    </div>
